storage:
  base_dir: "./tmp_storage"   # 存储目录

model:
  name: "gpt-4o-mini"         # 使用的语言模型
  api_key: "your-openai-api-key"  # OpenAI API 密钥
  max_tokens: 3000
  temperature: 0.7

book:
  pdf_file: "data/example_book.pdf"  # PDF 文件路径
  toc_start: 44                      # 目录起始页
  toc_end: 49                        # 目录结束页
  content_start: 50                  # 正文起始页
  content_end: 300                   # 正文结束页

retry:
  max_attempts: 3                    # 配置最大重试次数，推荐3次以上

prompts:
  knowledge_point_prompt: |
    我将为你提供一本书中的若干页的图片，请你从中提取多个知识点，并为每个知识点生成以下内容：
  
    1. `aliases`: 一个简短的别名，作为该知识点的标题，不超过10个字。
    2. `tags`: 默认包含 `概念` 标签，如果知识点涉及“实践”或“公式”相关内容，请添加 `实践` 或 `公式` 标签。
    3. `状态`: 所有知识点的初始状态为 `初见`。
    4. 将知识点的具体内容填充到 `记录点` 部分，这里可以是定义、概念、用法等，主要参考书本上对于这个知识点的描述，如果描述太少，可以自行添加
    5. 联想最多三个前置知识点和三个后继知识点，并分别填充到 `相关点` 部分。
    6. 复习点保持空白，这是用户自行填充的内容。
    7. 注意，你所提取到的每个知识点都需要生成一份如下的内容，且知识点之间要用`|||`分割，使用 `|||` 作为知识点之间的分隔符。
    8. 你不需要返回我所输入的内容
    9. 前面的aliases、tags、状态属于元数据，因此需要用“---”作为分割
    10. 对于每一页纸，至多提取两个知识点，因此你需要提取你认为最重要的，不要贪多
    11. 如果文中提及了公式，使用markdown的公式表示法：$$公式$$
    12. 如果是习题，则不视作知识点
  
    **示例（对于其中的内容只是起参考作用）：**
    
    ---
    aliases: 监督学习
    tags:
      - 概念
      - 实践
    状态:
      - 初见
    ---
    ## 复习点
  
    ---
    ## 记录点
    监督学习是一种通过标注数据集训练模型的方法。
  
    ---
    ## 相关点
    前置知识点：
    - 数据预处理
    - 线性回归
  
    后继知识点：
    - 无监督学习
    - 半监督学习
    ---
  toc_prompt: |
    请从以下目录图片中提取目录结构，并输出为符合 YAML 语法的格式。目录结构应支持多层级嵌套，具体格式如下：
    
    目录结构:
      - 章节名: [章节标题]
        页码范围: [起始页, 结束页]
        子章节:
          - 章节名: [子章节标题]
            页码范围: [起始页, 结束页]
            子章节:
              - 章节名: [更深层级的子章节标题]
                页码范围: [起始页, 结束页]
    
    生成要求：
    1. 尽可能捕捉所有的层级信息，不限制嵌套深度，不要去省略层级信息，同时章节的编号也不能省略，不然会出现很坏的事情
    2. 如果某个章节没有子章节，可以省略 `子章节` 字段，但是这个章节不能省略
    3. 页码范围应尽量准确，包含起始和结束页码。
    4. 请确保 YAML 格式正确，以便后续解析。
    5. 如果图片不完整，尽量根据已有信息生成目录结构。
    6. 章节不可跳过，正不然会出现很坏的事情
    7. 每一个章节名都需要带上一个对应的页码范围
    8. 对于章节标题的文本内容，不要出现双引号，不然会破坏yml格式
    9. 你不需要将书中的“第x部分”考虑为章节，如“第三部分”
    10. 你不可以回答除了yaml文件以外的任何内容，包括其他提示性语句